spring.application.name=HospitalmanagmentProject-1
server.port=${PORT:8080}
spring.datasource.url=jdbc:mysql://centerbeam.proxy.rlwy.net:12367/railway
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=PSDGmhSsIQASnSMcmJgIWQpmqRyBDvjp


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
SPRING_MAIL_HOST=smtp.gmail.com
SPRING_MAIL_PORT=587
SPRING_MAIL_USERNAME=ssivamyadav0123@gmail.com
SPRING_MAIL_PASSWORD=fvoh dhzz gfuw pxdd
SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
