spring.application.name=HospitalmanagmentProject-1
server.port=${PORT:8080}
spring.datasource.url=jdbc:mysql://localhost:3307/railway
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=mHbjhsAfzDczHtIbXtvxrGFqKIjHsQMU

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ssivamyadav0123@gmail.com
spring.mail.password=tjyb xzhc tcbm vsmo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
